# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - ls
      - echo Installing Yarn...
      - npm install yarn 
      - echo Installing typescript...
      - npm install typescript -g
  pre_build:
    commands:
      - echo Installing source dependencies...
      - yarn install
      - ls
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn build 
      - tsc -p ./src/server
      - ls
  post_build:
    commands:
      - echo Build completed on `date`
      - ls
# Include only the files required for your application to run.
artifacts:
  files:
    - 'dist/**/*'
    - package.json
    - node_modules/**/*
  # base-directory: 'dist'
